In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [10]:
import pandas as pd

print(pd.__version__)

2.2.3


In [12]:
df = pd.read_excel('./team.xlsx')

In [13]:
df

name team  Q1  Q2  Q3  Q4
0      Liver    E  89  21  24  64
1       Arry    C  36  37  37  57
2        Ack    A  57  60  18  84
3      Eorge    C  93  96  71  78
4        Oah    D  65  49  61  86
..       ...  ...  ..  ..  ..  ..
95   Gabriel    C  48  59  87  74
96   Austin7    C  21  31  30  43
97  Lincoln4    C  98  93   1  20
98       Eli    E  11  74  58  91
99       Ben    E  21  43  41  74

[100 rows x 6 columns]

In [14]:
df.head()

name team  Q1  Q2  Q3  Q4
0  Liver    E  89  21  24  64
1   Arry    C  36  37  37  57
2    Ack    A  57  60  18  84
3  Eorge    C  93  96  71  78
4    Oah    D  65  49  61  86

In [15]:
df.tail()


name team  Q1  Q2  Q3  Q4
95   Gabriel    C  48  59  87  74
96   Austin7    C  21  31  30  43
97  Lincoln4    C  98  93   1  20
98       Eli    E  11  74  58  91
99       Ben    E  21  43  41  74

In [16]:
df.sample(10)

name team  Q1  Q2  Q3  Q4
42     Dylan    A  86  87  65  20
39    Harley    B   2  99  12  13
5     Harlie    C  24  13  87  43
34   Reggie1    A  30  12  23   9
64   Harvey2    B  43  76  87  90
58     Lewis    B   4  34  77  28
82      Finn    E   4   1  55  32
29     Riley    E  35  26  59  83
24     Isaac    E  74  23  28  65
97  Lincoln4    C  98  93   1  20

In [17]:
df.shape

(100, 6)

In [19]:
print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    100 non-null    object
 1   team    100 non-null    object
 2   Q1      100 non-null    int64 
 3   Q2      100 non-null    int64 
 4   Q3      100 non-null    int64 
 5   Q4      100 non-null    int64 
dtypes: int64(4), object(2)
memory usage: 4.8+ KB
None


In [20]:
print(df.describe())


               Q1          Q2          Q3          Q4
count  100.000000  100.000000  100.000000  100.000000
mean    49.200000   52.550000   52.670000   52.780000
std     29.962603   29.845181   26.543677   27.818524
min      1.000000    1.000000    1.000000    2.000000
25%     19.500000   26.750000   29.500000   29.500000
50%     51.500000   49.500000   55.000000   53.000000
75%     74.250000   77.750000   76.250000   75.250000
max     98.000000   99.000000   99.000000   99.000000


In [21]:
print(df.dtypes)


name    object
team    object
Q1       int64
Q2       int64
Q3       int64
Q4       int64
dtype: object


In [22]:
print(df.axes)
print(df.columns)

[RangeIndex(start=0, stop=100, step=1), Index(['name', 'team', 'Q1', 'Q2', 'Q3', 'Q4'], dtype='object')]
Index(['name', 'team', 'Q1', 'Q2', 'Q3', 'Q4'], dtype='object')


In [25]:
df.set_index('team', inplace=True) 
df

Q2  Q3  Q4
team            
E     21  24  64
C     37  37  57
A     60  18  84
C     96  71  78
D     49  61  86
...   ..  ..  ..
C     59  87  74
C     31  30  43
C     93   1  20
E     74  58  91
E     43  41  74

[100 rows x 3 columns]

In [26]:
df = pd.read_excel('./team.xlsx')
df.set_index('team', inplace=True) 
df

name  Q1  Q2  Q3  Q4
team                          
E        Liver  89  21  24  64
C         Arry  36  37  37  57
A          Ack  57  60  18  84
C        Eorge  93  96  71  78
D          Oah  65  49  61  86
...        ...  ..  ..  ..  ..
C      Gabriel  48  59  87  74
C      Austin7  21  31  30  43
C     Lincoln4  98  93   1  20
E          Eli  11  74  58  91
E          Ben  21  43  41  74

[100 rows x 5 columns]

In [27]:
df['Q1']

team
E    89
C    36
A    57
C    93
D    65
     ..
C    48
C    21
C    98
E    11
E    21
Name: Q1, Length: 100, dtype: int64

In [28]:
df.Q1

team
E    89
C    36
A    57
C    93
D    65
     ..
C    48
C    21
C    98
E    11
E    21
Name: Q1, Length: 100, dtype: int64

In [30]:
df

name  Q1  Q2  Q3  Q4
team                          
E        Liver  89  21  24  64
C         Arry  36  37  37  57
A          Ack  57  60  18  84
C        Eorge  93  96  71  78
D          Oah  65  49  61  86
...        ...  ..  ..  ..  ..
C      Gabriel  48  59  87  74
C      Austin7  21  31  30  43
C     Lincoln4  98  93   1  20
E          Eli  11  74  58  91
E          Ben  21  43  41  74

[100 rows x 5 columns]

In [31]:
df[['team', 'Q1']]

KeyError: "['team'] not in index"

In [32]:
df = pd.read_excel('./team.xlsx')

In [33]:
df[['team', 'Q1']]

team  Q1
0     E  89
1     C  36
2     A  57
3     C  93
4     D  65
..  ...  ..
95    C  48
96    C  21
97    C  98
98    E  11
99    E  21

[100 rows x 2 columns]

In [34]:
df.loc[:, ['team', 'Q1']] 

team  Q1
0     E  89
1     C  36
2     A  57
3     C  93
4     D  65
..  ...  ..
95    C  48
96    C  21
97    C  98
98    E  11
99    E  21

[100 rows x 2 columns]

In [35]:
df.loc[:10, ['team', 'Q1']] 

team  Q1
0     E  89
1     C  36
2     A  57
3     C  93
4     D  65
5     C  24
6     B  61
7     A   9
8     D  64
9     A  77
10    B  17

In [36]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [37]:
df[df.index == 'Liver']

Empty DataFrame
Columns: [name, team, Q1, Q2, Q3, Q4]
Index: []

In [38]:
df

name team  Q1  Q2  Q3  Q4
0      Liver    E  89  21  24  64
1       Arry    C  36  37  37  57
2        Ack    A  57  60  18  84
3      Eorge    C  93  96  71  78
4        Oah    D  65  49  61  86
..       ...  ...  ..  ..  ..  ..
95   Gabriel    C  48  59  87  74
96   Austin7    C  21  31  30  43
97  Lincoln4    C  98  93   1  20
98       Eli    E  11  74  58  91
99       Ben    E  21  43  41  74

[100 rows x 6 columns]

In [39]:
df.set_index('team', inplace=True) 
df.index

Index(['E', 'C', 'A', 'C', 'D', 'C', 'B', 'A', 'D', 'A', 'B', 'B', 'C', 'C',
       'B', 'E', 'A', 'A', 'C', 'E', 'A', 'D', 'A', 'D', 'E', 'B', 'E', 'D',
       'C', 'E', 'B', 'E', 'C', 'C', 'A', 'B', 'E', 'C', 'B', 'B', 'A', 'E',
       'A', 'E', 'D', 'E', 'C', 'C', 'D', 'D', 'B', 'A', 'D', 'B', 'C', 'E',
       'B', 'D', 'B', 'D', 'B', 'E', 'C', 'D', 'B', 'D', 'D', 'A', 'D', 'D',
       'A', 'A', 'D', 'C', 'E', 'A', 'E', 'B', 'B', 'A', 'E', 'C', 'E', 'B',
       'B', 'B', 'C', 'C', 'A', 'D', 'E', 'C', 'B', 'B', 'D', 'C', 'C', 'C',
       'E', 'E'],
      dtype='object', name='team')

In [40]:
range(100)

range(0, 100)

In [42]:
df.index == 'A'

array([False, False,  True, False, False, False, False,  True, False,
        True, False, False, False, False, False, False,  True,  True,
       False, False,  True, False,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [43]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [44]:
for i in range(6):
    print(a[i])


1
2
3
4
5
6


In [45]:
a[:3][1]=100
a

array([  1, 100,   3,   4,   5,   6])

In [46]:
l=[1,2,3,4,5,6]
l[:3][1]=100
l


[1, 2, 3, 4, 5, 6]

In [1]:
l=[1,2,3]
l[0,2]

TypeError: list indices must be integers or slices, not tuple