In [2]:
import numpy as np

创建数组有 6 种常规机制：


从其他 Python 结构（即列表和元组）转换


内部 NumPy 数组创建函数（例如 arange、ones、zero 等）


复制、联接或更改现有数组


从磁盘读取数组，无论是标准格式还是自定义格式


通过使用字符串或缓冲区从原始字节创建数组


使用特殊的库函数（例如，随机）

In [3]:
np.array('123123')

array('123123', dtype='<U6')

In [4]:
np.array([1, 2, 3]).dtype

dtype('int64')

# 1 - 1D 数组创建函数

一维数组创建函数，例如 numpy.linspace 和 numpy.arange 通常需要至少两个输入，start 和 stop 。

# 2 - 2D 数组创建函数

2D 数组创建函数，例如 numpy.eye、numpy.diag 和 numpy.vander 定义表示为 2D 数组的特殊矩阵的属性。

np.eye（n， m） 定义 2D 单位矩阵。i=j（行索引和列索引相等）为 1 的元素为 0，其余元素为 0，如下所示：

In [5]:
print(np.eye(3))
print(np.eye(3,5))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


numpy.diag 可以定义一个沿对角线具有给定值的方形 2D 数组 ，或者如果给定一个 2D 数组，则返回一个仅是对角线元素的 1D 数组。在进行线性代数时，这两个数组创建函数可能会有所帮助，如下所示：

In [6]:
print(np.diag([1, 2, 3]))
print(np.diag([1, 2, 3], k=1))
print(np.diag([1, 2, 3,4], k=-1))
a=np.array([[1,2],[3,4]])
print(np.diag(a))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[1 4]


vander（x， n） 将 Vandermonde 矩阵定义为 2D NumPy 数组。每列 的 Vandermonde 矩阵是输入一维数组的递减幂，或者 list 或 tuple， x，其中最高多项式阶数为 n-1。此数组创建例程有助于生成线性最小二乘模型，如下所示：

In [7]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly s

In [8]:
print(np.vander(np.linspace(0, 2, 5), 10))

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00]
 [1.95312500e-03 3.90625000e-03 7.81250000e-03 1.56250000e-02
  3.12500000e-02 6.25000000e-02 1.25000000e-01 2.50000000e-01
  5.00000000e-01 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [3.84433594e+01 2.56289062e+01 1.70859375e+01 1.13906250e+01
  7.59375000e+00 5.06250000e+00 3.37500000e+00 2.25000000e+00
  1.50000000e+00 1.00000000e+00]
 [5.12000000e+02 2.56000000e+02 1.28000000e+02 6.40000000e+01
  3.20000000e+01 1.60000000e+01 8.00000000e+00 4.00000000e+00
  2.00000000e+00 1.00000000e+00]]


ndarray 创建函数，例如 numpy.ones， numpy.zeros 和 random 根据所需的形状定义数组。ndarray 创建函数可以通过指定 Tuples 或 List 中沿该维度的维度和长度来创建具有任何维度的数组。

numpy.indices 将创建一组数组（堆叠为高一维数组），每个维度一个，每个数组代表该维度的变体：

In [9]:
np.indices((2,2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

# 复制、连接或更改现有数组

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [11]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


# 4） 从磁盘读取数组，无论是标准格式还是自定义格式