In [2]:
import numpy as np

# 基本索引

In [3]:
np.unravel_index(99,(10,10))

(np.int64(9), np.int64(9))

单元素索引的工作方式与其他标准 Python 序列完全相同。它从 0 开始，并接受从数组末尾开始索引的负索引。
请注意，如果索引数少于维度数的多维数组编制索引，则会得到一个子维数组。例如：

需要注意的是，虽然第二种情况效率较低（因为会创建一个新的临时数组，该数组是在第一个索引之后生成的，随后再对其进行第二次索引），但 x[0, 2] 和 x[0][2] 是等价的。

NumPy的单元素索引规则与Python其他标准序列类型完全一致：

采用0基索引（即第一个元素的下标为0）

支持负值索引（-1表示最后一个元素，-2表示倒数第二个，以此类推）

多维索引无需分层书写（例如二维数组的x[1,2]完全等效于x[1][2]的写法）



# 切片和跨步
基础切片操作将Python的基础切片概念扩展至N维空间。当obj是以下对象时发生基础切片：

1. 切片对象（由中括号内的冒号表示法构造）
2. 整数
3. 切片对象与整数组成的元组
（允许穿插使用省略号...和newaxis对象）

核心特性：

1. 使用N个整数索引时，返回表示对应元素的数组标量
2. 遵循Python的零基索引规则：第i个索引的有效范围是0 ≤ ni < shape[i]
3. 负索引表示从数组末尾开始计数（如n_i < 0时等价于n_i + shape[i]）
4. 所有基础切片生成的数组都是原数组的视图（view）

▌ 重要技术说明：
NumPy切片与Python内置序列（字符串/元组/列表）不同，它创建视图而非副本。当从大型数组提取小片段时需特别注意：即使原数组不再使用，提取的小数组仍会保持对原数组内存的引用。此时建议显式调用copy()方法。

切片规则体系：
1. 标准切片语法i:j:k：
- i：起始索引（含）
- j：终止索引（不含）
- k：步长（默认1）
- 选定元素满足：i, i+k, ..., i+(m-1)k（其中m = floor((j-i)/k)+1）

2. 缺省值规则：
- 当k>0时：i默认为0，j默认为n（该维度长度）
- 当k<0时：i默认为n-1，j默认为-1
- :等价于::，表示选择该轴所有索引

3. 维度处理规则：
- 当选择元组对象数小于N时，缺失维度自动补全为:
- 整数索引会降低输出维度（效果等同于i:i+1但减少1个维度）

In [11]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x[1:7:2] ) # array([1, 3, 5])
print(x[-3:3:-1]) # array([7, 6, 5, 4])

# 多维切片
y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(y[1:3,:1] ) # 保留第1维度，其余全选

[1 3 5]
[7 6 5 4]
[[[4]]]


<b>高级特性：</b>
1. 可通过slice()对象动态构建切片：
```python
# 创建一个示例数组
x = np.arange(100).reshape(10, 10)  # 10x10的二维数组

# 使用slice对象构造切片
obj = (slice(1, 10, 5), slice(None, None, -1))

# 执行切片操作
result = x[obj]  # 等价于 x[1:10:5, ::-1]
```
2. 重要限制：
- 切片赋值时，右侧值必须与切片形状广播兼容
- 不可通过切片操作扩展数组维度

In [16]:
# 创建一个示例数组
x = np.arange(100).reshape(10, 10)  # 10x10的二维数组

# 使用slice对象构造切片
obj = (slice(1, 10, 5), slice(None, None, -1))

# 执行切片操作
result = x[obj]  # 等价于 x[1:10:5, ::-1]

print(result)

[[19 18 17 16 15 14 13 12 11 10]
 [69 68 67 66 65 64 63 62 61 60]]


slice(1, 10, 5)